// Auto-generated by build-sidecar.mjs, do not edit manually
export const BUILD_CONSTANTS: Record<string, string> = {
  "YOUCLAW_WEBSITE_URL": "https://youclaw.dev",
  "YOUCLAW_API_URL": "https://readmex.com",
  "YOUCLAW_BUILTIN_API_URL": "https://readmex.com/api",
  "YOUCLAW_BUILTIN_AUTH_TOKEN": "youclaw-builtin-cloud-model"
}
